services:
    db:
        build: .
        container_name: db
        restart: always
        ports:
            - "5432:5432"
        tty: true
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
